taskkill /f /im "SDSMan.exe"
taskkill /f /im "SDSMan64.exe"

cd C:\Windows\softcamp\sds

ren "ComAgent.exe.N00B" "ComAgent.exe"
ren "dscntsrv.exe.N00B" "dscntsrv.exe"
ren "DSGULdr.exe.N00B" "DSGULdr.exe"
ren "DSHLdr.exe.N00B" "DSHLdr.exe"
ren "DSImgVu.exe.N00B" "DSImgVu.exe"
ren "DSJED.exe.N00B" "DSJED.exe"
ren "DSLSChgr.exe.N00B" "DSLSChgr.exe"
ren "DSOHMAN.exe.N00B" "DSOHMAN.exe"
ren "DSOLESOM.exe.N00B" "DSOLESOM.exe"
ren "DSRegist.exe.N00B" "DSRegist.exe"
ren "DSSLdr.exe.N00B" "DSSLdr.exe"
ren "DSSOMMan.exe.N00B" "DSSOMMan.exe"
ren "DSSvcIns.exe.N00B" "DSSvcIns.exe"
ren "DSSysRun.exe.N00B" "DSSysRun.exe"
ren "DSTxtVu.exe.N00B" "DSTxtVu.exe"
ren "dsUpgradeClient.exe.N00B" "dsUpgradeClient.exe"
ren "MkSom.exe.N00B" "MkSom.exe"
ren "OffSend.exe.N00B" "OffSend.exe"
ren "pssetup.exe.N00B" "pssetup.exe"
ren "ScanEnc.exe.N00B" "ScanEnc.exe"
ren "SCLoader.exe.N00B" "SCLoader.exe"
ren "SCTL_MsgBox.exe.N00B" "SCTL_MsgBox.exe"
ren "SDSEnc.exe.N00B" "SDSEnc.exe"
ren "SDSEnv.exe.N00B" "SDSEnv.exe"
ren "SDSHlpr.exe.N00B" "SDSHlpr.exe"
ren "SDSIcon.exe.N00B" "SDSIcon.exe"
ren "SDSILog.exe.N00B" "SDSILog.exe"
ren "SDSLaunc.exe.N00B" "SDSLaunc.exe"
ren "SDSLogin.exe.N00B" "SDSLogin.exe"
ren "SDSMan.exe.N00B" "SDSMan.exe"
ren "SDSMkIM.exe.N00B" "SDSMkIM.exe"
ren "SDSMonitor4U.exe.N00B" "SDSMonitor4U.exe"
ren "SDSShl.exe.N00B" "SDSShl.exe"
ren "SecuPC.exe.N00B" "SecuPC.exe"
ren "SOM.exe.N00B" "SOM.exe"
ren "SomDeletor.exe.N00B" "SomDeletor.exe"
ren "SomXLdr.exe.N00B" "SomXLdr.exe"

cd C:\Windows\softcamp\sds\x64

ren "DSHLdr64.exe.N00B" "DSHLdr64.exe"
ren "DSOHMAN64.exe.N00B" "DSOHMAN64.exe"
ren "DSOLESOM64.exe.N00B" "DSOLESOM64.exe"
ren "DSSomMgr64.exe.N00B" "DSSomMgr64.exe"
ren "SDSMan64.exe.N00B" "SDSMan64.exe"
ren "SomXLdr64.exe.N00B" "SomXLdr64.exe"

pause
shutdown /r /t 5