taskkill /f /im "SDSMan.exe"
taskkill /f /im "SDSMan64.exe"
taskkill /f /im "SDSLogin.exe"

cd C:\Windows\softcamp\sds

ren "ComAgent.exe" "ComAgent.exe.N00B"
ren "dscntsrv.exe" "dscntsrv.exe.N00B"
ren "DSGULdr.exe" "DSGULdr.exe.N00B"
ren "DSHLdr.exe" "DSHLdr.exe.N00B"
ren "DSImgVu.exe" "DSImgVu.exe.N00B"
ren "DSJED.exe" "DSJED.exe.N00B"
ren "DSLSChgr.exe" "DSLSChgr.exe.N00B"
ren "DSOHMAN.exe" "DSOHMAN.exe.N00B"
ren "DSOLESOM.exe" "DSOLESOM.exe.N00B"
ren "DSRegist.exe" "DSRegist.exe.N00B"
ren "DSSLdr.exe" "DSSLdr.exe.N00B"
ren "DSSOMMan.exe" "DSSOMMan.exe.N00B"
ren "DSSvcIns.exe" "DSSvcIns.exe.N00B"
ren "DSSysRun.exe" "DSSysRun.exe.N00B"
ren "DSTxtVu.exe" "DSTxtVu.exe.N00B"
ren "dsUpgradeClient.exe" "dsUpgradeClient.exe.N00B"
ren "MkSom.exe" "MkSom.exe.N00B"
ren "OffSend.exe" "OffSend.exe.N00B"
ren "pssetup.exe" "pssetup.exe.N00B"
ren "ScanEnc.exe" "ScanEnc.exe.N00B"
ren "SCLoader.exe" "SCLoader.exe.N00B"
ren "SCTL_MsgBox.exe" "SCTL_MsgBox.exe.N00B"
ren "SDSEnc.exe" "SDSEnc.exe.N00B"
ren "SDSEnv.exe" "SDSEnv.exe.N00B"
ren "SDSHlpr.exe" "SDSHlpr.exe.N00B"
ren "SDSIcon.exe" "SDSIcon.exe.N00B"
ren "SDSILog.exe" "SDSILog.exe.N00B"
ren "SDSLaunc.exe" "SDSLaunc.exe.N00B"
ren "SDSLogin.exe" "SDSLogin.exe.N00B"
ren "SDSMan.exe" "SDSMan.exe.N00B"
ren "SDSMkIM.exe" "SDSMkIM.exe.N00B"
ren "SDSMonitor4U.exe" "SDSMonitor4U.exe.N00B"
ren "SDSShl.exe" "SDSShl.exe.N00B"
ren "SecuPC.exe" "SecuPC.exe.N00B"
ren "SOM.exe" "SOM.exe.N00B"
ren "SomDeletor.exe" "SomDeletor.exe.N00B"
ren "SomXLdr.exe" "SomXLdr.exe.N00B"

cd C:\Windows\softcamp\sds\x64

ren "DSHLdr64.exe" "DSHLdr64.exe.N00B"
ren "DSOHMAN64.exe" "DSOHMAN64.exe.N00B"
ren "DSOLESOM64.exe" "DSOLESOM64.exe.N00B"
ren "DSSomMgr64.exe" "DSSomMgr64.exe.N00B"
ren "SDSMan64.exe" "SDSMan64.exe.N00B"
ren "SomXLdr64.exe" "SomXLdr64.exe.N00B"

pause
shutdown /r /t 5